version: '3.8'

services:
  speakfree_frontend:
    volumes:
      - /app/node_modules
      - /src
      - ./frontend:/app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '5173:5173'
    networks:
      - frontend
      - speakfree

networks:
  speakfree:
    name: speakfree
  frontend: